name: Java Application CI/CD with deploy to Minikube

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'


    - name: Set Up Minikube
      run: |
         minikube start
         kubectl config use-context minikube



    - name: Start Minikube
      run: |
        minikube start --driver=none
        kubectl config use-context minikube

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/getting-started-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/getting-started-app:latest

    - name: Deploy to Minikube using manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Wait for Pod to be Ready
      run: |
        kubectl wait --for=condition=ready pod -l app=getting-started-app --timeout=120s

    - name: Get Pod Status
      run: kubectl get pods

    - name: Get Service Status
      run: kubectl get svc

    - name: Get Pod Logs
      run: |
        kubectl logs $(kubectl get pods -l app=getting-started-app -o jsonpath='{.items[0].metadata.name}')

    - name: Get Minikube Service URL
      run: minikube service getting-started-service --url
